first week
Alucard163/loft-taxi pull request #2
Opened 2022-08-21 10:52 UTC by Alucard163

Задание первой недели

2022-08-21 20:50 UTC, nlold requested changes
В целом, PR хороший. Очень хорошо для начального этапа построена архитектра и иерархия директорий. Объединение компонентов, CSS файлов и статики в одной директории — однозначный лайк. 

В основном, большая часть проблем связано с деструктуризацией стейта и передачей его в таком состоянии в компоненты — постарался описать подробности в комментах, но если необходима будет дополнительная информация, то пшии, расскажу подробнее.

Также обрати внимание на верстку — запустил проект у себя локально и хэдер выходит за рамки по ширине и высоте окна браузера из-за чего возникают "белые полосы" и появляется полоса прокрутки вертикальная и горизональная.

2022-08-21 20:50 UTC, nlold commented on src/components/app/App.jsx
> +                {showHeader && <Header setPage={this.setPage} {...this.state} />}
Вот такой подход с деструктуризацией state для передачи в props компонентов лучше избегать. Так это сильно снижает читаемость кода и явно непонятно, какие props передаются в компонент.

Поэтому лучше передавать данные явно, по аналогии с функцией setState.

2022-08-21 20:50 UTC, nlold commented on src/components/app/App.jsx
> +                <CurrentPage setPage={this.setPage} {...this.props} {...this.state}/>
Аналогичная ситуация. Лучше явно передавать необходимые компоненту пропсы.

2022-08-21 20:50 UTC, nlold commented on src/components/auth/Auth.jsx
> +    isLoginPage = this.props.page === 'login'
Вот эту переменную, лучше хранить в state комопнента, а не просто как метод класса. Так как хранение переменной в state позволит в дальшейшем, при увеличении сложности компонента, избежать потенциальный лишних ререндерингов.

2022-08-21 20:50 UTC, nlold commented on src/components/auth/Auth.jsx
> +                        {this.isLoginPage ? <LoginForm {...this.props}/> : <RegisterForm {...this.props}/> }
Аналогично, про деструктуризацию.

2022-08-21 20:50 UTC, nlold commented on src/components/forms/LoginForm/LoginForm.jsx
> +    state = { email: "", password: "" };
Инициализацию state лучше всего производит в конструктуре. 

Вот хорошая сслыка на документацию https://ru.reactjs.org/docs/react-component.html#constructor

2022-08-21 20:50 UTC, nlold commented on src/components/forms/LoginForm/LoginForm.jsx
> +        const { email, password } = this.state;
Очень хороший и правильный подход с деструктуризацией свойств. Лайк.

2022-08-21 20:50 UTC, nlold commented on src/components/forms/RegisterForm/RegisterForm.jsx
> +    state = { email: "", name: "", password: "" };
Аналогично. State лучше инициализировать в конструкторе.

2022-08-21 20:50 UTC, nlold commented on src/components/header/Header.jsx
> +    links = [
Так как этот массив статичный, то его можно вынести из компонента и изпользовать как внешнюю константу. В целом, это никак не влияет на его работу или производительность, но лучше такие константы выносить вне компонентов. Чтобы можно было проще читать код, а также возможно переиспользовать в других компонентах.

2022-08-21 20:50 UTC, nlold commented on src/components/header/Header.jsx
> +                            <li key={item.id} className={[styles.link, ...(this.isActive(item.key) ? styles.isActive : [])].join(' ')}>
Такие длинные вычисления лучше выносить в переменную внутри функции return, а в верстке уже использовать получившееся значение, чтобы было проще ее читать и работать с ней в будущем.

2022-08-21 20:50 UTC, nlold commented on src/pages/login/LoginPage.jsx
> +        return <>
Такой React.Fragment можно не использовать в этом случае, если нет необходимости рендерить несколько элементов на одном уровне без общего родителя.

https://ru.reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html

2022-08-21 20:50 UTC, nlold commented on src/pages/login/LoginPage.jsx
> +                <Auth {...this.props}/>
Аналогично с деструктуризацией.

2022-08-21 20:50 UTC, nlold commented on src/pages/map/MapPage.jsx
> +        return <>
Аналогично с Fragment.

2022-08-21 20:50 UTC, nlold commented on src/pages/registration/RegistrationPage.jsx
> +                <Auth {...this.props}/>
Аналогично с деструктуризацией.

2022-08-22 10:38 UTC, nlold requested changes

2022-08-22 10:38 UTC, nlold commented on src/components/auth/Auth.jsx
> +                        {isLoginPage ? <LoginForm setPage={this.props.setPage} page={this.props.page}/> : <RegisterForm setPage={this.props.setPage} page={this.props.page}/> }
Ты уже получил setPage из this.props, поэтому тут можно просто написать setPage вместо this.props.setPage.

Ну и аналогично с остальными props в этом и не только компоненте. Проверь, плиз еще раз.

2022-08-22 10:38 UTC, nlold commented on src/pages/login/LoginPage.jsx
> +                <Auth setPage={this.props.setPage} page={this.props.page}/>
Лучше получить свойства при помощи деструктуризации и передать дальше в этот компонент. 

По аналогии, как ты отлично сделал в `LoginForm.jsx`.

2022-08-22 10:38 UTC, nlold commented on src/pages/registration/RegistrationPage.jsx
> +                <Auth setPage={this.props.setPage} page={this.props.page}/>
Лучше получить свойства при помощи деструктуризации и передать дальше в этот компонент.

По аналогии, как ты отлично сделал в LoginForm.jsx.

2022-08-22 13:05 UTC, nlold approved these changes
Все гуд — апрув!

2022-08-22 13:05 UTC, merged

2022-08-29 05:27 UTC, Alucard163 commented
Привет, просьба посмотреть реквест второй недели
https://github.com/Alucard163/loft-taxi/pull/3

пн, 22 авг. 2022 г. в 16:05, Nik Liubitscky ***@***.***>:

> ***@***.**** approved this pull request.
>
> Все гуд — апрув!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Alucard163/loft-taxi/pull/2#pullrequestreview-1080448405>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHVHWHVRJDS4TYADL3ZF3MLV2N3IXANCNFSM57EX66FA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>