third week
Alucard163/loft-taxi pull request #4
Opened 2022-09-05 06:18 UTC by Alucard163

redux, api, auth

2022-09-05 11:07 UTC, nlold commented on src/components/auth/Auth.jsx
> +        if (isLoggedIn) {
По-тихоньку начинай переводить компоненты на функциональные, чтобы иметь доступ к хукам. Например, в это случае, лучше использовть хук useEffect, чтобы обработать такую логику.

2022-09-05 11:10 UTC, nlold commented on src/components/auth/Auth.jsx
> +                            {!isLoggedIn ? 'Войти' : 'Зарегистрироваться'}
Наверное, тут нужно ориентироватся не только на эту переменную. Кейс: если я не залогинен в приложении и хочу зарегистрироваться, то какой текст у меня будет? Тут и ниже.

2022-09-05 11:11 UTC, nlold commented on src/index.js
>  import './index.css';
Обрати внимание на порядок испортов. Лучше, сначала испортировать сторонние либы, а потом все остальное.

2022-09-05 11:12 UTC, nlold commented on src/store/index.js
> +import { configureStore } from "@reduxjs/toolkit";
Почему не используешь configureStore? createStore уже deprecated метод.

2022-09-05 11:13 UTC, nlold commented on src/reducers/auth.spec.js
> +    let state;
Лишняя переменная

2022-09-05 11:14 UTC, nlold commented on src/pages/login/LoginPage.jsx
>      }
Лучше отказаться от классовых компонентов в пользу функциональных

2022-09-05 11:16 UTC, nlold commented on src/middlewares/authMiddleware.spec.js
> +                const getToken = jest.fn();
Лишняя переменная

2022-09-05 11:18 UTC, nlold commented on src/components/forms/RegisterForm/RegisterForm.jsx
>  import { Box, Button, FormControl, FormHelperText, Input, InputLabel } from '@mui/material';
Лишний импорт

2022-09-05 11:19 UTC, nlold commented on src/api/api.js
> +    console.log(JSON.stringify(user));
console.log необходимо подчищать

2022-09-05 11:20 UTC, nlold commented on src/api/api.js
> +            console.log('Error: ' + e);
А вот в случае ошибок их можно оставить.

2022-09-05 11:20 UTC, nlold commented on src/api/api.js
> +        .then(data => {
отступы

2022-09-05 11:21 UTC, nlold commented on src/actions/types.js
> +export const LOG_IN = 'LOG_IN'
А почему не воспользовался всеми функциями redux/toolkit?

2022-09-05 11:36 UTC, nlold commented on src/components/forms/LoginForm/LoginForm.jsx
> +        props.authenticate(email, password);
Нет надобности прокидывать в props redux-actions. Доступ к ним лучше осуществялть нарпямую.

2022-09-05 11:43 UTC, nlold requested changes
Помимо комментов обрати внимание на флоу авторизации — поднял проект у себя, попробовал зарегистрироватся и ничего не происходит.

Также обращай внимание на то, что подсказывает линтер — неиспользуемые переменные, лишние console.log, отступы и так далее. Много таких простых замечаний, которые можно избежать.

По остальному функционалу — все ОК.

2022-09-05 13:54 UTC, Alucard163 commented on src/reducers/auth.spec.js
> +    let state;
это не лишняя переменная, она как раз используется в тесте и передается параметром в authReducer, без нее придется каждый раз инициализировать новую переменную.

2022-09-08 12:19 UTC, nlold approved these changes
Все супер — апрув!

2022-09-08 12:21 UTC, merged